# Generated by Django 4.1.2 on 2022-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateTimeField(null=True, verbose_name='data published')),
                ('body', models.CharField(max_length=255)),
            ],
        ),
    ]
